#!/bin/zsh -e

branch_name="$1"
[[ -n "$branch_name" ]] || (
	>&2 echo "Usage: $0 <branch-name>"
	exit 1
)

root=$(git worktree list --porcelain | perl -lne 'm[^worktree (.*)/.bare$] and print $1')
[[ -n "$root" ]] || exit 1

if [[ ! -d "$root/$branch_name" ]]; then
	git worktree add "$root/$branch_name" "$branch_name" >&2
fi

echo "$root/$branch_name"
